### ISSUE TITLE
The generated configure script should be excluded

### ISSUE THREAD

**Issue by jserv** [dryman/opic#10]
The script file `configure` was generated by Automake, and it should not exist in source listing. Instead, place the following autogen script:
```
#! /bin/sh
AUTORECONF_ARGS=-i
mkdir -p m4
AUTORECONF_ARGS="$AUTORECONF_ARGS -I m4"
autoreconf $AUTORECONF_ARGS
rm -rf autom4te.cache
```

**Comment by dryman** [comment]
Thanks for the suggestion. Just [googled autogen][autogen], I probably would rename it as bootstrap.sh.

[autogen]: https://www.gnu.org/software/automake/faq/autotools-faq.html#What-does-_002e_002fbootstrap-or-_002e_002fautogen_002esh-do_003f
